// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYuQBdQI8By0X558zOtzWDHF_tJvIdi7U',
    appId: '1:1068574295689:web:5903863765611d5da6a858',
    messagingSenderId: '1068574295689',
    projectId: 'pushmedium-72c8c',
    authDomain: 'pushmedium-72c8c.firebaseapp.com',
    storageBucket: 'pushmedium-72c8c.appspot.com',
    measurementId: 'G-LKD38QV2RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9xDlRloK2HC-NNMVxIOegnoDADb1D89M',
    appId: '1:1068574295689:android:d8824e120fff778ea6a858',
    messagingSenderId: '1068574295689',
    projectId: 'pushmedium-72c8c',
    storageBucket: 'pushmedium-72c8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrB14kEmSrRNnuPSkVInssmqLjW9yyDKM',
    appId: '1:1068574295689:ios:eb685b1628112de4a6a858',
    messagingSenderId: '1068574295689',
    projectId: 'pushmedium-72c8c',
    storageBucket: 'pushmedium-72c8c.appspot.com',
    iosBundleId: 'com.example.pushy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrB14kEmSrRNnuPSkVInssmqLjW9yyDKM',
    appId: '1:1068574295689:ios:eb685b1628112de4a6a858',
    messagingSenderId: '1068574295689',
    projectId: 'pushmedium-72c8c',
    storageBucket: 'pushmedium-72c8c.appspot.com',
    iosBundleId: 'com.example.pushy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYuQBdQI8By0X558zOtzWDHF_tJvIdi7U',
    appId: '1:1068574295689:web:cc1e46c39ee61f6fa6a858',
    messagingSenderId: '1068574295689',
    projectId: 'pushmedium-72c8c',
    authDomain: 'pushmedium-72c8c.firebaseapp.com',
    storageBucket: 'pushmedium-72c8c.appspot.com',
    measurementId: 'G-5FHW0SXW5Q',
  );
}
